# Generated by Django 4.1.13 on 2024-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=600)),
                ('document_url', models.CharField(max_length=600)),
                ('document_pdf', models.FileField(upload_to='pdf/')),
                ('publish_id', models.CharField(max_length=600)),
                ('publish_name', models.CharField(max_length=600)),
                ('authors_name', models.CharField(max_length=600)),
                ('publish_type', models.CharField(max_length=600)),
                ('publication_type', models.CharField(max_length=600)),
                ('publication_date', models.CharField(max_length=600)),
                ('publisher_name', models.CharField(max_length=600)),
                ('key_words', models.CharField(max_length=600)),
                ('summary', models.CharField(max_length=600)),
                ('reference', models.CharField(max_length=600)),
                ('number_of_citations', models.DecimalField(decimal_places=0, max_digits=10)),
                ('doi_number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
