# Generated by Django 5.0.2 on 2024-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('document_url', models.CharField(blank=True, max_length=200, null=True)),
                ('document_pdf', models.FileField(blank=True, upload_to='pdf/')),
            ],
        ),
    ]
