# Generated by Django 4.1.13 on 2024-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=200)),
                ('document_url', models.CharField(max_length=200)),
                ('document_pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
